### ISSUE TITLE
Mod not showing in game options

### ISSUE THREAD

**Issue by drvonbubbleboots** [antonpup/PAYDAY-2-BetterLightFX#1]
I have followed the instructions on how to install the mod into Payday 2and it doesn't show under the "Mod options" in game...any ideas on how to fix this?

**Comment by antonpup** [comment]
Do you have anything in the error log?

**Comment by drvonbubbleboots** [comment]
Thanks for getting back to me!

To go over what I have done so far:
-installed the Payday 2 BLT mod 
-extracted the files for LightFX extender and pasted them into the Payday 2 folder 
-in game go to advanced video settings and enable Alienware Light FX

From this point when the game launches my keyboard (Razer Deathstalker Chroma) changed colour to green but there is no option in “mod options” to make any changes to settings. It also sometimes goes from green to red when an assault starts in game, so something is working but not everything...

Attached is a log file from the mods/logs folder for me starting the game up and attempting to reach the options for the mod...

Thanks for any help!

Dan

**Comment by antonpup** [comment]
You didn't install BetterLightFX mod for blt. You did all other steps correctly though!

**Comment by drvonbubbleboots** [comment]
AWESOME!

Thanks!
