### ISSUE TITLE
Crash on starup

### ISSUE THREAD

**Issue by Spodi** [antonpup/PAYDAY-2-BetterLightFX#2]
With this mod enabled version 1.51.4 (u99.1) payday2 crashes on starup

```
Application has crashed: C++ exception
mods/BetterLightFX/Hooks/NetworkAccountSteam.lua:16: attempt to index field '_masks' (a nil value)
```

**Comment by antonpup** [comment]
Resolved with [V1.0.2](https://github.com/antonpup/PAYDAY-2-BetterLightFX/releases/tag/v1.0.2).
